### ISSUE TITLE
Get rid of illegal reflective access warning in ec2 admin

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#77] opened 2021-02-17 17:06 UTC
The ec2 admin raises an illegal reflective access message when it reports any other problem such as trying to delete something that does not exist or runs into a permission problem.

```
Terminating the selected instances in region 'eu-central-1' ... WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.amazonaws.util.XpathUtils (file:/home/anyone/projects/loadtest/xlt-5.3.0/lib/aws-java-sdk-core-1.11.762.jar) to method com.sun.org.apache.xpath.internal.XPathContext.getDTMManager()
WARNING: Please consider reporting this to the maintainers of com.amazonaws.util.XpathUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Failed: No instances specified (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 23234-3bd3-4157-b365-4bf7b4432221ec7)
```

**Comment by h-arlt** [comment] 2021-02-17 18:08
The Illegal access warning is caused by 3rd-party library aws-sdk-java. 
According to their issue tracker (https://github.com/aws/aws-sdk-java/issues/1603), it won't be fixed for v1 but should be fixed in v2 of the library. Until we update to v2, there isn't anything we can do here.

**Comment by jowerner** [comment] 2021-04-19 13:12
At least we can suppress these warnings by passing the appropriate command line options to java, the same way we did for `mastercontroller.sh`, `agentcontroller.sh`, and `agent.sh`.

**Closed** 2021-04-21 17:20 UTC
Labels: enhancement
